spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pharmacyWarehouseDB
    username: nadezhda
    password: nadezhda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    show-sql: true
  liquibase:
    change-log: classpath:changelog-master.xml
    enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

